[tool.poetry]
name = "langbrainscore"
version = "0.1.0"
description = ""
authors = ["Greta Tuckute <gretatu@mit.edu>", 
           "Aalok Sathe <asathe@mit.edu>", 
           "Ben Lipkin <lipkinb@mit.edu>"]
license = "MIT"
exclude = ["langbrainscore/data/"]


[tool.poetry.dependencies]
python = "3.8.*"
tqdm = "^4.62.3"
transformers = "4.10.0"
torch = "^1.9.1"
torchvision = "^0.10.1"
torchaudio = "^0.9.1"
numpy = "^1.21.2"
colorama = "^0.4.4"
pandas = "^1.3.4"
scikit-learn = "^1.0.1"
xarray = "^0.20.0"


[tool.poetry.dev-dependencies]
pdoc3 = "^0.10.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"